<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><OutputType>Exe</OutputType><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><ProjectReference Include="../../src/PdfSpace.Pdf/PdfSpace.Pdf.csproj"/><ProjectReference Include="../../src/PdfSpace.Editing/PdfSpace.Editing.csproj" /><ProjectReference Include="../../src/PdfSpace.Skia/PdfSpace.Skia.csproj" /><PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="3.119.4" /><ProjectReference Include="../../src/PdfSpace.Ocr/PdfSpace.Ocr.csproj"/></ItemGroup></Project>
